/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVehicleRouteImport } from './routes/admin.vehicle'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRutasRouteImport } from './routes/admin.rutas'
import { Route as AdminMovilizacionRouteImport } from './routes/admin.movilizacion'
import { Route as AdminEntradasSalidasRouteImport } from './routes/admin.entradas-salidas'
import { Route as AdminCierreDiarioRouteImport } from './routes/admin.cierre-diario'
import { Route as AdminChoferRouteImport } from './routes/admin.chofer'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehicleRoute = AdminVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRutasRoute = AdminRutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMovilizacionRoute = AdminMovilizacionRouteImport.update({
  id: '/movilizacion',
  path: '/movilizacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntradasSalidasRoute = AdminEntradasSalidasRouteImport.update({
  id: '/entradas-salidas',
  path: '/entradas-salidas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCierreDiarioRoute = AdminCierreDiarioRouteImport.update({
  id: '/cierre-diario',
  path: '/cierre-diario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChoferRoute = AdminChoferRouteImport.update({
  id: '/chofer',
  path: '/chofer',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chofer': typeof AdminChoferRoute
  '/admin/cierre-diario': typeof AdminCierreDiarioRoute
  '/admin/entradas-salidas': typeof AdminEntradasSalidasRoute
  '/admin/movilizacion': typeof AdminMovilizacionRoute
  '/admin/rutas': typeof AdminRutasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chofer': typeof AdminChoferRoute
  '/admin/cierre-diario': typeof AdminCierreDiarioRoute
  '/admin/entradas-salidas': typeof AdminEntradasSalidasRoute
  '/admin/movilizacion': typeof AdminMovilizacionRoute
  '/admin/rutas': typeof AdminRutasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chofer': typeof AdminChoferRoute
  '/admin/cierre-diario': typeof AdminCierreDiarioRoute
  '/admin/entradas-salidas': typeof AdminEntradasSalidasRoute
  '/admin/movilizacion': typeof AdminMovilizacionRoute
  '/admin/rutas': typeof AdminRutasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle': typeof AdminVehicleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/chofer'
    | '/admin/cierre-diario'
    | '/admin/entradas-salidas'
    | '/admin/movilizacion'
    | '/admin/rutas'
    | '/admin/users'
    | '/admin/vehicle'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/chofer'
    | '/admin/cierre-diario'
    | '/admin/entradas-salidas'
    | '/admin/movilizacion'
    | '/admin/rutas'
    | '/admin/users'
    | '/admin/vehicle'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/chofer'
    | '/admin/cierre-diario'
    | '/admin/entradas-salidas'
    | '/admin/movilizacion'
    | '/admin/rutas'
    | '/admin/users'
    | '/admin/vehicle'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicle': {
      id: '/admin/vehicle'
      path: '/vehicle'
      fullPath: '/admin/vehicle'
      preLoaderRoute: typeof AdminVehicleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rutas': {
      id: '/admin/rutas'
      path: '/rutas'
      fullPath: '/admin/rutas'
      preLoaderRoute: typeof AdminRutasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movilizacion': {
      id: '/admin/movilizacion'
      path: '/movilizacion'
      fullPath: '/admin/movilizacion'
      preLoaderRoute: typeof AdminMovilizacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entradas-salidas': {
      id: '/admin/entradas-salidas'
      path: '/entradas-salidas'
      fullPath: '/admin/entradas-salidas'
      preLoaderRoute: typeof AdminEntradasSalidasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cierre-diario': {
      id: '/admin/cierre-diario'
      path: '/cierre-diario'
      fullPath: '/admin/cierre-diario'
      preLoaderRoute: typeof AdminCierreDiarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chofer': {
      id: '/admin/chofer'
      path: '/chofer'
      fullPath: '/admin/chofer'
      preLoaderRoute: typeof AdminChoferRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChoferRoute: typeof AdminChoferRoute
  AdminCierreDiarioRoute: typeof AdminCierreDiarioRoute
  AdminEntradasSalidasRoute: typeof AdminEntradasSalidasRoute
  AdminMovilizacionRoute: typeof AdminMovilizacionRoute
  AdminRutasRoute: typeof AdminRutasRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehicleRoute: typeof AdminVehicleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChoferRoute: AdminChoferRoute,
  AdminCierreDiarioRoute: AdminCierreDiarioRoute,
  AdminEntradasSalidasRoute: AdminEntradasSalidasRoute,
  AdminMovilizacionRoute: AdminMovilizacionRoute,
  AdminRutasRoute: AdminRutasRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehicleRoute: AdminVehicleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
